Hosts:
  Etcd:
    Address:
      - 127.0.0.1:2379
    RegisterTTL: 50
    RegisterInterval: 17
  Mysql:
    Host: 127.0.0.1:3306
    User: root
    Pass: root
    DBName: mobile_account
    IfShowSql: true
    IfSyncDB: true
ServiceName: FishingGateway
Project: Qingyun
Env: prod
Version: 0.0.1
